# Generated by Django 4.1 on 2023-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnemScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TP_SEXO_MASCULINO", models.BooleanField(default=False)),
                (
                    "TP_ESTADO_CIVIL",
                    models.CharField(
                        choices=[
                            (1, "Solteiro"),
                            (2, "Casado"),
                            (3, "Divorciado"),
                            (4, "Separado"),
                            (5, "Viuvo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "TP_ENSINO",
                    models.CharField(
                        choices=[
                            (1, "Ensino Regular"),
                            (2, "Educação Especial - Modalidade Substitutiva"),
                            (3, "Educação de Jovens e Adultos"),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "TP_ANO_CONCLUIU",
                    models.CharField(
                        choices=[
                            (0, "Não informado"),
                            (1, "2019"),
                            (2, "2018"),
                            (3, "2017"),
                            (4, "2016"),
                            (5, "2015"),
                            (6, "2014"),
                            (7, "2013"),
                            (8, "2012"),
                            (9, "2011"),
                            (10, "2010"),
                            (11, "2009"),
                            (12, "2008"),
                            (13, "2007"),
                            (14, "Antes de 2007"),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "TP_LOCALIZACAO_ESC",
                    models.CharField(
                        choices=[(1, "Urbana"), (2, "Rural")], max_length=300
                    ),
                ),
                (
                    "TP_ST_CONCLUSAO",
                    models.IntegerField(
                        choices=[
                            (1, "Já concluí o Ensino Médio"),
                            (2, "Estou cursando e concluirei o Ensino Médio em 2020"),
                            (3, "Estou cursando e concluirei o Ensino Médio após 2020"),
                            (4, "Não concluí e não estou cursando o Ensino Médio"),
                        ]
                    ),
                ),
                (
                    "Q001",
                    models.CharField(
                        choices=[
                            ("A", "Nunca estudou"),
                            (
                                "B",
                                "Não completou a 4ª série/5º ano do Ensino Fundamental",
                            ),
                            (
                                "C",
                                "Completou a 4ª série/5º ano, mas não completou a 8ª série/9º ano do Ensino Fundamental",
                            ),
                            (
                                "D",
                                "Completou a 8ª série/9º ano do Ensino Fundamental, mas não completou o Ensino Médio",
                            ),
                            (
                                "E",
                                "Completou o Ensino Médio, mas não completou a Faculdade",
                            ),
                            (
                                "F",
                                "Completou a Faculdade, mas não completou a Pós-graduação",
                            ),
                            ("G", "Completou a Pós-graduação"),
                            ("H", "Não sei"),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "Q002",
                    models.CharField(
                        choices=[
                            ("A", "Nunca estudou"),
                            (
                                "B",
                                "Não completou a 4ª série/5º ano do Ensino Fundamental",
                            ),
                            (
                                "C",
                                "Completou a 4ª série/5º ano, mas não completou a 8ª série/9º ano do Ensino Fundamental",
                            ),
                            (
                                "D",
                                "Completou a 8ª série/9º ano do Ensino Fundamental, mas não completou o Ensino Médio",
                            ),
                            (
                                "E",
                                "Completou o Ensino Médio, mas não completou a Faculdade",
                            ),
                            (
                                "F",
                                "Completou a Faculdade, mas não completou a Pós-graduação",
                            ),
                            ("G", "Completou a Pós-graduação"),
                            ("H", "Não sei"),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "TP_ESCOLA",
                    models.CharField(
                        choices=[
                            (1, "Não respondeu"),
                            (2, "Pública"),
                            (3, "Privada"),
                            (4, "Exterior"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Q003",
                    models.CharField(
                        choices=[
                            (
                                1,
                                "Lavrador, agricultor sem empregados, bóia fria, criador de animais (gado, porcos, galinhas, ovelhas, cavalos etc.), apicultor, pescador, lenhador, seringueiro, extrativista.",
                            ),
                            (
                                2,
                                "Diarista, empregado doméstico, cuidador de idosos, babá, cozinheiro (em casas particulares), motorista particular, jardineiro, faxineiro de empresas e prédios, vigilante, porteiro, carteiro, office-boy, vendedor, caixa, atendente de loja, auxiliar administrativo, recepcionista, servente de pedreiro, repositor de mercadoria.",
                            ),
                            (
                                3,
                                "Padeiro, cozinheiro industrial ou em restaurantes, sapateiro, costureiro, joalheiro, torneiro mecânico, operador de máquinas, soldador, operário de fábrica, trabalhador da mineração, pedreiro, pintor, eletricista, encanador, motorista, caminhoneiro, taxista.",
                            ),
                            (
                                4,
                                "Professor (de ensino fundamental ou médio, idioma, música, artes etc.), técnico (de enfermagem, contabilidade, eletrônica etc.), policial, militar de baixa patente (soldado, cabo, sargento), corretor de imóveis, supervisor, gerente, mestre de obras, pastor, microempresário (proprietário de empresa com menos de 10 empregados), pequeno comerciante, pequeno proprietário de terras, trabalhador autônomo ou por conta própria.",
                            ),
                            (
                                5,
                                "Médico, engenheiro, dentista, psicólogo, economista, advogado, juiz, promotor, defensor, delegado, tenente, capitão, coronel, professor universitário, diretor em empresas públicas ou privadas, político, proprietário de empresas com mais de 10 empregados.",
                            ),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "Q004",
                    models.CharField(
                        choices=[
                            (
                                1,
                                "Lavrador, agricultor sem empregados, bóia fria, criador de animais (gado, porcos, galinhas, ovelhas, cavalos etc.), apicultor, pescador, lenhador, seringueiro, extrativista.",
                            ),
                            (
                                2,
                                "Diarista, empregado doméstico, cuidador de idosos, babá, cozinheiro (em casas particulares), motorista particular, jardineiro, faxineiro de empresas e prédios, vigilante, porteiro, carteiro, office-boy, vendedor, caixa, atendente de loja, auxiliar administrativo, recepcionista, servente de pedreiro, repositor de mercadoria.",
                            ),
                            (
                                3,
                                "Padeiro, cozinheiro industrial ou em restaurantes, sapateiro, costureiro, joalheiro, torneiro mecânico, operador de máquinas, soldador, operário de fábrica, trabalhador da mineração, pedreiro, pintor, eletricista, encanador, motorista, caminhoneiro, taxista.",
                            ),
                            (
                                4,
                                "Professor (de ensino fundamental ou médio, idioma, música, artes etc.), técnico (de enfermagem, contabilidade, eletrônica etc.), policial, militar de baixa patente (soldado, cabo, sargento), corretor de imóveis, supervisor, gerente, mestre de obras, pastor, microempresário (proprietário de empresa com menos de 10 empregados), pequeno comerciante, pequeno proprietário de terras, trabalhador autônomo ou por conta própria.",
                            ),
                            (
                                5,
                                "Médico, engenheiro, dentista, psicólogo, economista, advogado, juiz, promotor, defensor, delegado, tenente, capitão, coronel, professor universitário, diretor em empresas públicas ou privadas, político, proprietário de empresas com mais de 10 empregados.",
                            ),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "Q005",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                            (13, "13"),
                            (14, "14"),
                            (15, "15"),
                            (16, "16"),
                            (17, "17"),
                            (18, "18"),
                            (19, "19"),
                            (20, "20"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Q008",
                    models.IntegerField(
                        choices=[
                            (1, "Não"),
                            (2, "Sim, um"),
                            (3, "Sim, dos"),
                            (4, "Sim, tres"),
                            (5, "Sim, quatro ou mais"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "Q006",
                    models.CharField(
                        choices=[
                            ("A", "Nenhuma Renda"),
                            ("B", "Até R$ 1.045,00"),
                            ("C", "De R$ 1.045,01 até R$ 1.567,50"),
                            ("D", "De R$ 1.567,51 até R$ 2.090,00"),
                            ("E", "De R$ 2.090,01 até R$ 2.612,50"),
                            ("F", "De R$ 2.612,51 até R$ 3.135,00"),
                            ("G", "De R$ 3.135,01 até R$ 4.180,00"),
                            ("H", "De R$ 4.180,01 até R$ 5.225,00"),
                            ("I", "De R$ 5.225,01 até R$ 6.270,00"),
                            ("J", "De R$ 6.270,01 até R$ 7.315,00"),
                            ("K", "De R$ 7.315,01 até R$ 8.360,00"),
                            ("L", "De R$ 8.360,01 até R$ 9.405,00"),
                            ("M", "De R$ 9.405,01 até R$ 10.450,00"),
                            ("N", "De R$ 10.450,01 até R$ 12.540,00"),
                            ("O", "De R$ 12.540,01 até R$ 15.675,00"),
                            ("P", "De R$ 15.675,01 até R$ 20.900,00"),
                            ("Q", "Acima de R$ 20.900,00"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "Q012",
                    models.CharField(
                        choices=[
                            (1, "Não"),
                            (2, "Sim, uma."),
                            (3, "Sim, duas."),
                            (4, "Sim, três."),
                            (5, "Sim, quatro ou mais."),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "Q022",
                    models.CharField(
                        choices=[
                            (1, "Não."),
                            (2, "Sim, um."),
                            (3, "Sim, dois."),
                            (4, "Sim, três."),
                            (5, "Sim, quatro ou mais."),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "Q024",
                    models.IntegerField(
                        choices=[
                            (1, "Não"),
                            (2, "Sim, um"),
                            (3, "Sim, dos"),
                            (4, "Sim, tres"),
                            (5, "Sim, quatro ou mais"),
                        ],
                        max_length=20,
                    ),
                ),
                ("Q025", models.BooleanField(default=False)),
                (
                    "TP_FAIXA_ETARIA",
                    models.CharField(
                        choices=[
                            (1, "Menor de 17 anos"),
                            (2, "17 anos"),
                            (3, "18 anos"),
                            (4, "19 anos"),
                            (5, "20 anos"),
                            (6, "21 anos"),
                            (7, "22 anos"),
                            (8, "23 anos"),
                            (9, "24 anos"),
                            (10, "25 anos"),
                            (11, "Entre 26 e 30 anos"),
                            (12, "Entre 31 e 35 anos"),
                            (13, "Entre 36 e 40 anos"),
                            (14, "Entre 41 e 45 anos"),
                            (15, "Entre 46 e 50 anos"),
                            (16, "Entre 51 e 55 anos"),
                            (17, "Entre 56 e 60 anos"),
                            (18, "Entre 61 e 65 anos"),
                            (19, "Entre 66 e 70 anos"),
                            (20, "Maior de 70 anos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "TP_COR_RACA",
                    models.CharField(
                        choices=[
                            ("0", "Não declarado"),
                            ("1", "Branca"),
                            ("2", "Preta"),
                            ("3", "Parda"),
                            ("4", "Amarela"),
                            ("5", "Indígena"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
