# Generated by Django 4.2.1 on 2023-05-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0002_alter_enemscore_q001_alter_enemscore_q002_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemscore',
            name='TP_SEXO_MASCULINO',
            field=models.IntegerField(choices=[(1, 'Menor de 17 anos'), (2, '17 anos'), (3, '18 anos'), (4, '19 anos'), (5, '20 anos'), (6, '21 anos'), (7, '22 anos'), (8, '23 anos'), (9, '24 anos'), (10, '25 anos'), (11, 'Entre 26 e 30 anos'), (12, 'Entre 31 e 35 anos'), (13, 'Entre 36 e 40 anos'), (14, 'Entre 41 e 45 anos'), (15, 'Entre 46 e 50 anos'), (16, 'Entre 51 e 55 anos'), (17, 'Entre 56 e 60 anos'), (18, 'Entre 61 e 65 anos'), (19, 'Entre 66 e 70 anos'), (20, 'Maior de 70 anos')]),
        ),
    ]
