# Generated by Django 4.2.1 on 2023-05-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0003_alter_enemscore_tp_sexo_masculino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemscore',
            name='Q025',
            field=models.IntegerField(choices=[(1, 'Não'), (2, 'Sim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enemscore',
            name='TP_SEXO_MASCULINO',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')]),
        ),
    ]
