# Generated by Django 4.2.1 on 2023-06-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0004_alter_enemscore_q025_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemscore',
            name='TP_ANO_CONCLUIU',
            field=models.IntegerField(choices=[(0, 'Não informado'), (1, '2022'), (2, '2021'), (3, '2020'), (4, '2019'), (5, '2018'), (6, '2017'), (7, '2016'), (8, '2015'), (9, '2014'), (10, '2013'), (11, '2012'), (12, '2011'), (13, '2010'), (14, '2009'), (15, '2008'), (16, '2007'), (17, 'Antes de 2007')], max_length=300),
        ),
        migrations.AlterField(
            model_name='enemscore',
            name='TP_ST_CONCLUSAO',
            field=models.IntegerField(choices=[(1, 'Já concluí o Ensino Médio'), (2, 'Estou cursando e concluirei o Ensino Médio'), (3, 'Estou cursando e concluirei o Ensino Médio'), (4, 'Não concluí e não estou cursando o Ensino Médio')]),
        ),
    ]
